pool: Windows

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '15.x'
- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: '$(knownHostsEntry)'
    sshPublicKey: '$(publicKey)'
    sshPassphrase: 'passphrase'
    sshKeySecureFile: 'ssh-key'
- script: |
    git config user.name "DaniilShmelev"
    git config user.email $(primaryGithubEmail)
- script: ssh-add -l -E sha256
- script: ssh -vT git@github.com
- script: npm install
- script: npm run build
- script: npx gh-pages -d dist -r git@github.com:DaniilShmelev/gh-pages-test.git
