pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '15.x'
- task: InstallSSHKeyFix@0
  inputs:
    knownHostsEntry: '$(knownHostsEntry)'
    sshKeySecureFile: 'gh-pages-test-private-key'
- script: |
    git config user.name "DaniilShmelev"
    git config user.email $(primaryGithubEmail)
- script: npm install
- script: npm run build
- script: npx gh-pages -d dist -r git@github.com:DaniilShmelev/gh-pages-test.git
